<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net472;net8.0-windows</TargetFrameworks>
        <OutputType>library</OutputType>
        <RootNamespace>ShowMeTheXAML.AvalonEdit</RootNamespace>
        <AssemblyName>ShowMeTheXAML.AvalonEdit</AssemblyName>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <UseWpf>True</UseWpf>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    </PropertyGroup>

    <PropertyGroup>
        <Title>ShowMeTheXAML.AvalonEdit</Title>
        <Description>AvalonEdit style for the ShowMeTheXAML XamlDisplay control.</Description>
        <Copyright>Copyright 2025</Copyright>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageIcon>icon.png</PackageIcon>
        <IncludeSymbols>True</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <RepositoryUrl>https://github.com/Keboo/ShowMeTheXAML</RepositoryUrl>
        <Authors>Kevin Bost</Authors>
    </PropertyGroup>
    
    <ItemGroup Condition="$(TargetFramework) == 'net472'">
        <Reference Include="System.Xml.Linq" />
        <Reference Include="System.Xaml" />
        <Reference Include="WindowsBase" />
        <Reference Include="PresentationCore" />
        <Reference Include="PresentationFramework" />
    </ItemGroup>
    <ItemGroup>
        <None Include="Properties\Settings.settings">
            <Generator>SettingsSingleFileGenerator</Generator>
            <LastGenOutput>Settings.Designer.cs</LastGenOutput>
        </None>
        <None Include="..\icon.png" Pack="true" PackagePath="\" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\ShowMeTheXAML\ShowMeTheXAML.csproj" PrivateAssets="None" />
    </ItemGroup>
</Project>