<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net472;net8.0-windows</TargetFrameworks>
        <OutputType>library</OutputType>
        <RootNamespace>ShowMeTheXAML</RootNamespace>
        <AssemblyName>ShowMeTheXAML</AssemblyName>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <UseWpf>true</UseWpf>
    </PropertyGroup>

    <PropertyGroup>
        <Title>ShowMeTheXAML</Title>
        <Description>Base classes for ShowMeTheXAML. This contains the basic control. If you are wanting to add this to your own project use ShowMeTheXAML.MSBuild.</Description>
        <Copyright>Copyright 2025</Copyright>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageIcon>icon.png</PackageIcon>
        <IncludeSymbols>True</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <RepositoryUrl>https://github.com/Keboo/ShowMeTheXAML</RepositoryUrl>
        <Authors>Kevin Bost</Authors>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\icon.png" Pack="true" PackagePath="\" />
    </ItemGroup>
</Project>